project:
  type: website

website:
  title: "Colin Fraser"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right: 
      - icon: envelope
        href: mailto://colin.r.fraser@gmail.com
      - icon: twitter
        href: https://twitter.com/colin_fraser
      - icon: linkedin
        href: https://linkedin.com/in/colin-fraser/
      - icon: medium
        href: https://medium.com/@colin.fraser
      - icon: github
        href: https://github.com/colin-fraser
      - text: threads
        href: https://www.threads.net/@colinfraser
  site-url: colin-fraser.net
  google-analytics: "G-6QW9PMVM0W"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

links:
  twitter: https://twitter.com/colin-fraser

