project:
  type: website

website:
  title: "Colin Fraser"
  navbar:
    left:
      - text: "Posts"
        href: index.qmd
      - href: about.qmd
    right: 
      - icon: envelope
        href: mailto:colin@123mail.org
      - text: "![](/assets/BlueskyLogo.svg){width=19.7px height=19.7px style='vertical-align: middle;'}"
        href: https://bsky.app/profile/colin-fraser.net
      - icon: twitter
        href: https://twitter.com/colin_fraser
      - icon: linkedin
        href: https://linkedin.com/in/colin-fraser/
      - icon: medium
        href: https://medium.com/@colin.fraser
      - icon: github
        href: https://github.com/colin-fraser
  site-url: https://colin-fraser.net
  google-analytics: "G-6QW9PMVM0W"

execute:
  freeze: auto

format:
  html:
    theme: simplex
    template-partials:
     - custom_partials/title-metadata.html
    css: styles.css
    toc: false
    encoding: utf-8