baseURL = "https://colin-fraser.net"
title = "Colin Fraser"
theme = "etch"
languageCode = "en-CA"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
PygmentsStyle = "default"

[params]
  description = "Colin Fraser's Website"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20
    
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    title = "projects"
    url = "/projects/"
    weight = 30

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true