baseurl = "https://colin-fraser.net/"
languageCode = "en-us"
title = "Colin Fraser's Website"
theme = "ghostwriter"
googleAnalytics = "UA-156563898-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "Colin Fraser"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[social]
    github  = "https://github.com/colin-fraser"
    twitter = "https://twitter.com/colin_fraser"
    linkedin = "https://www.linkedin.com/in/colin-fraser-a8692210/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Radlibrary"
    url = "/2020/01/19/radlibrary/"
    weight = 4
[[menu.main]]
    name = "COVID-19 In Canada"
    url = "/2020/03/27/tracking-covid-19-in-canada/"
    weight = 5

[params]
    description = "Colin Fraser. Data scientist at Facebook."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
    github = "https://github.com/colin-fraser"
    twitter = "https://www.twitter.com/colin_fraser"
    linkedin = "https://www.linkedin.com/in/colin-fraser/"
    
    dateformat = "2006-01-02"
    shareGooglePlus = false


    # [params.logo]
    # url = "logo.png"
    # width = 50
    # height = 50
    # alt = "Logo"

